// ASTBuilder.swift
// Visitor for building AST from parse tree

import Antlr4

/// Builds AST from parse tree generated by ANTLR
class ASTBuilder: stellaParserBaseListener {
    
    // Stacks for accumulating results when traversing a tree
    private var programStack: [Program] = []
    private var declStack: [Decl] = []
    private var exprStack: [Expr] = []
    private var typeStack: [Type] = []
    private var patternStack: [Pattern] = []
    private var paramDeclStack: [ParamDecl] = []
    private var bindingStack: [Binding] = []
    private var patternBindingStack: [PatternBinding] = []
    private var matchCaseStack: [MatchCase] = []
    private var labelledPatternStack: [LabelledPattern] = []
    private var recordFieldTypeStack: [RecordFieldType] = []
    private var variantFieldTypeStack: [VariantFieldType] = []
    
    private var languageDecl: LanguageDecl = .core
    private var extensions: [Extension] = []
    
    // Result of construction
    private(set) var program: Program?
    
    // MARK: - Helper Methods
    
    private func getPosition(_ ctx: ParserRuleContext) -> SourcePosition {
        guard let start = ctx.getStart() else {
            return .unknown
        }
        return SourcePosition(line: start.getLine(), column: start.getCharPositionInLine())
    }
    
    // MARK: - Program
    
    override func exitProgram(_ ctx: stellaParser.ProgramContext) {
        let decls = ctx.decls.compactMap { _ in declStack.isEmpty ? nil : declStack.removeFirst() }
        program = Program(
            languageDecl: languageDecl,
            extensions: extensions,
            decls: decls
        )
    }
    
    // MARK: - Language Declaration
    
    override func exitLanguageCore(_ ctx: stellaParser.LanguageCoreContext) {
        languageDecl = .core
    }
    
    // MARK: - Extensions
    
    override func exitAnExtension(_ ctx: stellaParser.AnExtensionContext) {
        let names = ctx.extensionNames.compactMap { $0.getText() }
        extensions.append(Extension(names: names))
    }
    
    // MARK: - Declarations
    
    override func exitDeclFun(_ ctx: stellaParser.DeclFunContext) {
        guard let returnExpr = exprStack.popLast() else {
            fatalError("Missing return expression in function declaration")
        }
        
        // Local declarations (reversed order)
        let localDeclCount = ctx.localDecls.count
        let localDecls = (0..<localDeclCount).compactMap { _ in declStack.popLast() }.reversed()
        
        // Return type (optional)
        let returnType = ctx.returnType != nil ? typeStack.popLast() : nil
        
        // Parameters
        let paramCount = ctx.paramDecls.count
        let params = (0..<paramCount).compactMap { _ in paramDeclStack.popLast() }.reversed()
        
        let name = ctx.name?.getText() ?? ""
        let position = getPosition(ctx)
        
        let decl = Decl.declFun(
            name: name,
            paramDecls: Array(params),
            returnType: returnType,
            localDecls: Array(localDecls),
            returnExpr: returnExpr,
            position: position
        )
        
        declStack.append(decl)
    }
    
    // MARK: - Parameter Declarations
    
    override func exitParamDecl(_ ctx: stellaParser.ParamDeclContext) {
        guard let paramType = typeStack.popLast() else {
            fatalError("Missing parameter type")
        }
        
        let name = ctx.name?.getText() ?? ""
        let position = getPosition(ctx)
        
        let param = ParamDecl(name: name, paramType: paramType, position: position)
        paramDeclStack.append(param)
    }
    
    // MARK: - Types
    
    override func exitTypeBool(_ ctx: stellaParser.TypeBoolContext) {
        typeStack.append(.bool)
    }
    
    override func exitTypeNat(_ ctx: stellaParser.TypeNatContext) {
        typeStack.append(.nat)
    }
    
    override func exitTypeUnit(_ ctx: stellaParser.TypeUnitContext) {
        typeStack.append(.unit)
    }
    
    override func exitTypeFun(_ ctx: stellaParser.TypeFunContext) {
        guard let returnType = typeStack.popLast() else {
            fatalError("Missing return type in function type")
        }
        
        let paramCount = ctx.paramTypes.count
        let paramTypes = (0..<paramCount).compactMap { _ in typeStack.popLast() }.reversed()
        
        typeStack.append(.function(paramTypes: Array(paramTypes), returnType: returnType))
    }
    
    override func exitTypeTuple(_ ctx: stellaParser.TypeTupleContext) {
        let typeCount = ctx.types.count
        let types = (0..<typeCount).compactMap { _ in typeStack.popLast() }.reversed()
        
        typeStack.append(.tuple(Array(types)))
    }
    
    override func exitTypeRecord(_ ctx: stellaParser.TypeRecordContext) {
        let fieldCount = ctx.fieldTypes.count
        let fields = (0..<fieldCount).compactMap { _ in recordFieldTypeStack.popLast() }.reversed()
        
        typeStack.append(.record(Array(fields)))
    }
    
    override func exitTypeSum(_ ctx: stellaParser.TypeSumContext) {
        guard let right = typeStack.popLast(),
              let left = typeStack.popLast() else {
            fatalError("Missing types in sum type")
        }
        
        typeStack.append(.sum(left: left, right: right))
    }
    
    override func exitTypeList(_ ctx: stellaParser.TypeListContext) {
        guard let elemType = typeStack.popLast() else {
            fatalError("Missing element type in list type")
        }
        
        typeStack.append(.list(elemType))
    }
    
    override func exitTypeVariant(_ ctx: stellaParser.TypeVariantContext) {
        let fieldCount = ctx.fieldTypes.count
        let fields = (0..<fieldCount).compactMap { _ in variantFieldTypeStack.popLast() }.reversed()
        
        typeStack.append(.variant(Array(fields)))
    }
    
    override func exitTypeParens(_ ctx: stellaParser.TypeParensContext) {
        // Parentheses are just for grouping, type is already on stack
    }
    
    // MARK: - Record Field Types
    
    override func exitRecordFieldType(_ ctx: stellaParser.RecordFieldTypeContext) {
        guard let fieldType = typeStack.popLast() else {
            fatalError("Missing field type in record field")
        }
        
        let label = ctx.label?.getText() ?? ""
        recordFieldTypeStack.append(RecordFieldType(label: label, fieldType: fieldType))
    }
    
    // MARK: - Variant Field Types
    
    override func exitVariantFieldType(_ ctx: stellaParser.VariantFieldTypeContext) {
        let label = ctx.label?.getText() ?? ""
        let fieldType = typeStack.popLast() // can be nil for nullary labels
        
        variantFieldTypeStack.append(VariantFieldType(label: label, fieldType: fieldType))
    }
    
    // MARK: - Expressions - Literals
    
    override func exitConstTrue(_ ctx: stellaParser.ConstTrueContext) {
        exprStack.append(.constTrue(getPosition(ctx)))
    }
    
    override func exitConstFalse(_ ctx: stellaParser.ConstFalseContext) {
        exprStack.append(.constFalse(getPosition(ctx)))
    }
    
    override func exitConstInt(_ ctx: stellaParser.ConstIntContext) {
        let value = Int(ctx.n?.getText() ?? "0") ?? 0
        exprStack.append(.constInt(value, getPosition(ctx)))
    }
    
    override func exitConstUnit(_ ctx: stellaParser.ConstUnitContext) {
        exprStack.append(.constUnit(getPosition(ctx)))
    }
    
    // MARK: - Expressions - Variables
    
    override func exitVar(_ ctx: stellaParser.VarContext) {
        let name = ctx.name?.getText() ?? ""
        exprStack.append(.variable(name, getPosition(ctx)))
    }
    
    // MARK: - Expressions - Functions
    
    override func exitAbstraction(_ ctx: stellaParser.AbstractionContext) {
        guard let returnExpr = exprStack.popLast() else {
            fatalError("Missing return expression in abstraction")
        }
        
        let paramCount = ctx.paramDecls.count
        let params = (0..<paramCount).compactMap { _ in paramDeclStack.popLast() }.reversed()
        
        exprStack.append(.abstraction(
            paramDecls: Array(params),
            returnExpr: returnExpr,
            getPosition(ctx)
        ))
    }
    
    override func exitApplication(_ ctx: stellaParser.ApplicationContext) {
        let argCount = ctx.args.count
        let args = (0..<argCount).compactMap { _ in exprStack.popLast() }.reversed()
        
        guard let fun = exprStack.popLast() else {
            fatalError("Missing function in application")
        }
        
        exprStack.append(.application(
            fun: fun,
            args: Array(args),
            getPosition(ctx)
        ))
    }
    
    // MARK: - Expressions - Conditionals
    
    override func exitIf(_ ctx: stellaParser.IfContext) {
        guard let elseExpr = exprStack.popLast(),
              let thenExpr = exprStack.popLast(),
              let condition = exprStack.popLast() else {
            fatalError("Missing expressions in if statement")
        }
        
        exprStack.append(.ifExpr(
            condition: condition,
            thenExpr: thenExpr,
            elseExpr: elseExpr,
            getPosition(ctx)
        ))
    }
    
    // MARK: - Expressions - Natural Numbers
    
    override func exitSucc(_ ctx: stellaParser.SuccContext) {
        guard let n = exprStack.popLast() else {
            fatalError("Missing expression in succ")
        }
        
        exprStack.append(.succ(n, getPosition(ctx)))
    }
    
    override func exitPred(_ ctx: stellaParser.PredContext) {
        guard let n = exprStack.popLast() else {
            fatalError("Missing expression in pred")
        }
        
        exprStack.append(.pred(n, getPosition(ctx)))
    }
    
    override func exitIsZero(_ ctx: stellaParser.IsZeroContext) {
        guard let n = exprStack.popLast() else {
            fatalError("Missing expression in iszero")
        }
        
        exprStack.append(.isZero(n, getPosition(ctx)))
    }
    
    override func exitNatRec(_ ctx: stellaParser.NatRecContext) {
        guard let step = exprStack.popLast(),
              let initial = exprStack.popLast(),
              let n = exprStack.popLast() else {
            fatalError("Missing expressions in natRec")
        }
        
        exprStack.append(.natRec(
            n: n,
            initial: initial,
            step: step,
            getPosition(ctx)
        ))
    }
    
    // MARK: - Expressions - Let Bindings
    
    override func exitLet(_ ctx: stellaParser.LetContext) {
        guard let body = exprStack.popLast() else {
            fatalError("Missing body in let expression")
        }
        
        let bindingCount = ctx.patternBindings.count
        let bindings = (0..<bindingCount).compactMap { _ in patternBindingStack.popLast() }.reversed()
        
        exprStack.append(.letExpr(
            bindings: Array(bindings),
            body: body,
            getPosition(ctx)
        ))
    }
    
    override func exitLetRec(_ ctx: stellaParser.LetRecContext) {
        guard let body = exprStack.popLast() else {
            fatalError("Missing body in letrec expression")
        }
        
        let bindingCount = ctx.patternBindings.count
        let bindings = (0..<bindingCount).compactMap { _ in patternBindingStack.popLast() }.reversed()
        
        exprStack.append(.letRec(
            bindings: Array(bindings),
            body: body,
            getPosition(ctx)
        ))
    }
    
    override func exitPatternBinding(_ ctx: stellaParser.PatternBindingContext) {
        guard let rhs = exprStack.popLast(),
              let pattern = patternStack.popLast() else {
            fatalError("Missing pattern or rhs in pattern binding")
        }
        
        patternBindingStack.append(PatternBinding(pattern: pattern, rhs: rhs))
    }
    
    // MARK: - Expressions - Type Ascription
    
    override func exitTypeAsc(_ ctx: stellaParser.TypeAscContext) {
        guard let type = typeStack.popLast(),
              let expr = exprStack.popLast() else {
            fatalError("Missing expression or type in type ascription")
        }
        
        exprStack.append(.typeAsc(
            expr: expr,
            type: type,
            getPosition(ctx)
        ))
    }
    
    // MARK: - Expressions - Tuples
    
    override func exitTuple(_ ctx: stellaParser.TupleContext) {
        let exprCount = ctx.exprs.count
        let exprs = (0..<exprCount).compactMap { _ in exprStack.popLast() }.reversed()
        
        exprStack.append(.tuple(Array(exprs), getPosition(ctx)))
    }
    
    override func exitDotTuple(_ ctx: stellaParser.DotTupleContext) {
        guard let expr = exprStack.popLast() else {
            fatalError("Missing expression in tuple projection")
        }
        
        let index = Int(ctx.index?.getText() ?? "1") ?? 1
        exprStack.append(.dotTuple(
            expr: expr,
            index: index,
            getPosition(ctx)
        ))
    }
    
    // MARK: - Expressions - Records
    
    override func exitRecord(_ ctx: stellaParser.RecordContext) {
        let bindingCount = ctx.bindings.count
        let bindings = (0..<bindingCount).compactMap { _ in bindingStack.popLast() }.reversed()
        
        exprStack.append(.record(Array(bindings), getPosition(ctx)))
    }
    
    override func exitBinding(_ ctx: stellaParser.BindingContext) {
        guard let rhs = exprStack.popLast() else {
            fatalError("Missing rhs in binding")
        }
        
        let name = ctx.name?.getText() ?? ""
        bindingStack.append(Binding(name: name, rhs: rhs))
    }
    
    override func exitDotRecord(_ ctx: stellaParser.DotRecordContext) {
        guard let expr = exprStack.popLast() else {
            fatalError("Missing expression in record projection")
        }
        
        let label = ctx.label?.getText() ?? ""
        exprStack.append(.dotRecord(
            expr: expr,
            label: label,
            getPosition(ctx)
        ))
    }
    
    // MARK: - Expressions - Sum Types
    
    override func exitInl(_ ctx: stellaParser.InlContext) {
        guard let expr = exprStack.popLast() else {
            fatalError("Missing expression in inl")
        }
        
        exprStack.append(.inl(expr, getPosition(ctx)))
    }
    
    override func exitInr(_ ctx: stellaParser.InrContext) {
        guard let expr = exprStack.popLast() else {
            fatalError("Missing expression in inr")
        }
        
        exprStack.append(.inr(expr, getPosition(ctx)))
    }
    
    override func exitMatch(_ ctx: stellaParser.MatchContext) {
        let caseCount = ctx.cases.count
        let cases = (0..<caseCount).compactMap { _ in matchCaseStack.popLast() }.reversed()
        
        guard let expr = exprStack.popLast() else {
            fatalError("Missing expression in match")
        }
        
        exprStack.append(.match(
            expr: expr,
            cases: Array(cases),
            getPosition(ctx)
        ))
    }
    
    override func exitMatchCase(_ ctx: stellaParser.MatchCaseContext) {
        guard let expr = exprStack.popLast(),
              let pattern = patternStack.popLast() else {
            fatalError("Missing pattern or expression in match case")
        }
        
        matchCaseStack.append(MatchCase(pattern: pattern, expr: expr))
    }
    
    // MARK: - Expressions - Lists
    
    override func exitList(_ ctx: stellaParser.ListContext) {
        let exprCount = ctx.exprs.count
        let exprs = (0..<exprCount).compactMap { _ in exprStack.popLast() }.reversed()
        
        exprStack.append(.list(Array(exprs), getPosition(ctx)))
    }
    
    override func exitConsList(_ ctx: stellaParser.ConsListContext) {
        guard let tail = exprStack.popLast(),
              let head = exprStack.popLast() else {
            fatalError("Missing head or tail in cons")
        }
        
        exprStack.append(.consList(
            head: head,
            tail: tail,
            getPosition(ctx)
        ))
    }
    
    override func exitHead(_ ctx: stellaParser.HeadContext) {
        guard let list = exprStack.popLast() else {
            fatalError("Missing list in head")
        }
        
        exprStack.append(.head(list, getPosition(ctx)))
    }
    
    override func exitTail(_ ctx: stellaParser.TailContext) {
        guard let list = exprStack.popLast() else {
            fatalError("Missing list in tail")
        }
        
        exprStack.append(.tail(list, getPosition(ctx)))
    }
    
    override func exitIsEmpty(_ ctx: stellaParser.IsEmptyContext) {
        guard let list = exprStack.popLast() else {
            fatalError("Missing list in isEmpty")
        }
        
        exprStack.append(.isEmpty(list, getPosition(ctx)))
    }
    
    // MARK: - Expressions - Variants
    
    override func exitVariant(_ ctx: stellaParser.VariantContext) {
        let expr = exprStack.popLast() // cna be nil for nullary variants
        let label = ctx.label?.getText() ?? ""
        
        exprStack.append(.variant(
            label: label,
            expr: expr,
            getPosition(ctx)
        ))
    }
    
    // MARK: - Expressions - Fixpoint
    
    override func exitFix(_ ctx: stellaParser.FixContext) {
        guard let expr = exprStack.popLast() else {
            fatalError("Missing expression in fix")
        }
        
        exprStack.append(.fix(expr, getPosition(ctx)))
    }
    
    // MARK: - Expressions - Arithmetic Operators
    
    override func exitAdd(_ ctx: stellaParser.AddContext) {
        guard let right = exprStack.popLast(),
              let left = exprStack.popLast() else {
            fatalError("Missing operands in add")
        }
        
        exprStack.append(.add(left: left, right: right, getPosition(ctx)))
    }
    
    override func exitSubtract(_ ctx: stellaParser.SubtractContext) {
        guard let right = exprStack.popLast(),
              let left = exprStack.popLast() else {
            fatalError("Missing operands in subtract")
        }
        
        exprStack.append(.subtract(left: left, right: right, getPosition(ctx)))
    }
    
    override func exitMultiply(_ ctx: stellaParser.MultiplyContext) {
        guard let right = exprStack.popLast(),
              let left = exprStack.popLast() else {
            fatalError("Missing operands in multiply")
        }
        
        exprStack.append(.multiply(left: left, right: right, getPosition(ctx)))
    }
    
    override func exitDivide(_ ctx: stellaParser.DivideContext) {
        guard let right = exprStack.popLast(),
              let left = exprStack.popLast() else {
            fatalError("Missing operands in divide")
        }
        
        exprStack.append(.divide(left: left, right: right, getPosition(ctx)))
    }
    
    // MARK: - Expressions - Logic Operators
    
    override func exitLogicNot(_ ctx: stellaParser.LogicNotContext) {
        guard let expr = exprStack.popLast() else {
            fatalError("Missing expression in not")
        }
        
        exprStack.append(.logicNot(expr, getPosition(ctx)))
    }
    
    override func exitLogicAnd(_ ctx: stellaParser.LogicAndContext) {
        guard let right = exprStack.popLast(),
              let left = exprStack.popLast() else {
            fatalError("Missing operands in and")
        }
        
        exprStack.append(.logicAnd(left: left, right: right, getPosition(ctx)))
    }
    
    override func exitLogicOr(_ ctx: stellaParser.LogicOrContext) {
        guard let right = exprStack.popLast(),
              let left = exprStack.popLast() else {
            fatalError("Missing operands in or")
        }
        
        exprStack.append(.logicOr(left: left, right: right, getPosition(ctx)))
    }
    
    // MARK: - Expressions - Comparison Operators
    
    override func exitLessThan(_ ctx: stellaParser.LessThanContext) {
        guard let right = exprStack.popLast(),
              let left = exprStack.popLast() else {
            fatalError("Missing operands in less than")
        }
        
        exprStack.append(.lessThan(left: left, right: right, getPosition(ctx)))
    }
    
    override func exitLessThanOrEqual(_ ctx: stellaParser.LessThanOrEqualContext) {
        guard let right = exprStack.popLast(),
              let left = exprStack.popLast() else {
            fatalError("Missing operands in less than or equal")
        }
        
        exprStack.append(.lessThanOrEqual(left: left, right: right, getPosition(ctx)))
    }
    
    override func exitGreaterThan(_ ctx: stellaParser.GreaterThanContext) {
        guard let right = exprStack.popLast(),
              let left = exprStack.popLast() else {
            fatalError("Missing operands in greater than")
        }
        
        exprStack.append(.greaterThan(left: left, right: right, getPosition(ctx)))
    }
    
    override func exitGreaterThanOrEqual(_ ctx: stellaParser.GreaterThanOrEqualContext) {
        guard let right = exprStack.popLast(),
              let left = exprStack.popLast() else {
            fatalError("Missing operands in greater than or equal")
        }
        
        exprStack.append(.greaterThanOrEqual(left: left, right: right, getPosition(ctx)))
    }
    
    override func exitEqual(_ ctx: stellaParser.EqualContext) {
        guard let right = exprStack.popLast(),
              let left = exprStack.popLast() else {
            fatalError("Missing operands in equal")
        }
        
        exprStack.append(.equal(left: left, right: right, getPosition(ctx)))
    }
    
    override func exitNotEqual(_ ctx: stellaParser.NotEqualContext) {
        guard let right = exprStack.popLast(),
              let left = exprStack.popLast() else {
            fatalError("Missing operands in not equal")
        }
        
        exprStack.append(.notEqual(left: left, right: right, getPosition(ctx)))
    }
    
    // MARK: - Expressions - Sequencing
    
    override func exitSequence(_ ctx: stellaParser.SequenceContext) {
        guard let expr2 = exprStack.popLast(),
              let expr1 = exprStack.popLast() else {
            fatalError("Missing expressions in sequence")
        }
        
        exprStack.append(.sequence(
            expr1: expr1,
            expr2: expr2,
            getPosition(ctx)
        ))
    }
    
    // MARK: - Expressions - Parenthesised
    
    override func exitParenthesisedExpr(_ ctx: stellaParser.ParenthesisedExprContext) {
        guard let expr = exprStack.popLast() else {
            fatalError("Missing expression in parentheses")
        }
        
        exprStack.append(.parenthesised(expr, getPosition(ctx)))
    }
    
    // MARK: - Patterns
    
    override func exitPatternVar(_ ctx: stellaParser.PatternVarContext) {
        let name = ctx.name?.getText() ?? ""
        patternStack.append(.patternVar(name, getPosition(ctx)))
    }
    
    override func exitPatternInt(_ ctx: stellaParser.PatternIntContext) {
        let value = Int(ctx.n?.getText() ?? "0") ?? 0
        patternStack.append(.patternInt(value, getPosition(ctx)))
    }
    
    override func exitPatternSucc(_ ctx: stellaParser.PatternSuccContext) {
        guard let pattern = patternStack.popLast() else {
            fatalError("Missing pattern in succ pattern")
        }
        
        patternStack.append(.patternSucc(pattern, getPosition(ctx)))
    }
    
    override func exitPatternTrue(_ ctx: stellaParser.PatternTrueContext) {
        patternStack.append(.patternTrue(getPosition(ctx)))
    }
    
    override func exitPatternFalse(_ ctx: stellaParser.PatternFalseContext) {
        patternStack.append(.patternFalse(getPosition(ctx)))
    }
    
    override func exitPatternUnit(_ ctx: stellaParser.PatternUnitContext) {
        patternStack.append(.patternUnit(getPosition(ctx)))
    }
    
    override func exitPatternInl(_ ctx: stellaParser.PatternInlContext) {
        guard let pattern = patternStack.popLast() else {
            fatalError("Missing pattern in inl pattern")
        }
        
        patternStack.append(.patternInl(pattern, getPosition(ctx)))
    }
    
    override func exitPatternInr(_ ctx: stellaParser.PatternInrContext) {
        guard let pattern = patternStack.popLast() else {
            fatalError("Missing pattern in inr pattern")
        }
        
        patternStack.append(.patternInr(pattern, getPosition(ctx)))
    }
    
    override func exitPatternTuple(_ ctx: stellaParser.PatternTupleContext) {
        let patternCount = ctx.patterns.count
        let patterns = (0..<patternCount).compactMap { _ in patternStack.popLast() }.reversed()
        
        patternStack.append(.patternTuple(Array(patterns), getPosition(ctx)))
    }
    
    override func exitPatternRecord(_ ctx: stellaParser.PatternRecordContext) {
        let patternCount = ctx.patterns.count
        let patterns = (0..<patternCount).compactMap { _ in labelledPatternStack.popLast() }.reversed()
        
        patternStack.append(.patternRecord(Array(patterns), getPosition(ctx)))
    }
    
    override func exitLabelledPattern(_ ctx: stellaParser.LabelledPatternContext) {
        guard let pattern = patternStack.popLast() else {
            fatalError("Missing pattern in labelled pattern")
        }
        
        let label = ctx.label?.getText() ?? ""
        labelledPatternStack.append(LabelledPattern(label: label, pattern: pattern))
    }
    
    override func exitPatternList(_ ctx: stellaParser.PatternListContext) {
        let patternCount = ctx.patterns.count
        let patterns = (0..<patternCount).compactMap { _ in patternStack.popLast() }.reversed()
        
        patternStack.append(.patternList(Array(patterns), getPosition(ctx)))
    }
    
    override func exitPatternCons(_ ctx: stellaParser.PatternConsContext) {
        guard let tail = patternStack.popLast(),
              let head = patternStack.popLast() else {
            fatalError("Missing patterns in cons pattern")
        }
        
        patternStack.append(.patternCons(
            head: head,
            tail: tail,
            getPosition(ctx)
        ))
    }
    
    override func exitPatternVariant(_ ctx: stellaParser.PatternVariantContext) {
        let pattern = patternStack.popLast() // can be nil for nullary variants
        let label = ctx.label?.getText() ?? ""
        
        patternStack.append(.patternVariant(
            label: label,
            pattern: pattern,
            getPosition(ctx)
        ))
    }
    
    override func exitPatternAsc(_ ctx: stellaParser.PatternAscContext) {
        guard let type = typeStack.popLast(),
              let pattern = patternStack.popLast() else {
            fatalError("Missing pattern or type in pattern ascription")
        }
        
        patternStack.append(.patternAsc(
            pattern: pattern,
            type: type,
            getPosition(ctx)
        ))
    }
    
    // MARK: - Stage 3: Types (#type-reconstruction, #universal-types)

    /// auto — placeholder type for type reconstruction
    override func exitTypeAuto(_ ctx: stellaParser.TypeAutoContext) {
        typeStack.append(.auto)
    }

    /// Type variable (X, Y, etc.) used in universal types
    override func exitTypeVar(_ ctx: stellaParser.TypeVarContext) {
        let name = ctx.name?.getText() ?? ""
        typeStack.append(.typeVar(name: name))
    }

    /// forall X Y. T — universally quantified type
    override func exitTypeForAll(_ ctx: stellaParser.TypeForAllContext) {
        guard let bodyType = typeStack.popLast() else {
            fatalError("Missing body type in TypeForAll")
        }
        let typeVars = ctx.types.compactMap { $0.getText() }
        typeStack.append(.forAll(typeVars: typeVars, bodyType: bodyType))
    }

    // MARK: - Stage 3: Declarations (#universal-types)

    /// generic fn name[T](...) -> RetType { ... }
    override func exitDeclFunGeneric(_ ctx: stellaParser.DeclFunGenericContext) {
        guard let returnExpr = exprStack.popLast() else {
            fatalError("Missing return expression in generic function declaration")
        }

        let localDeclCount = ctx.localDecls.count
        let localDecls = (0..<localDeclCount).compactMap { _ in declStack.popLast() }.reversed()
        let returnType = ctx.returnType != nil ? typeStack.popLast() : nil
        let paramCount = ctx.paramDecls.count
        let params = (0..<paramCount).compactMap { _ in paramDeclStack.popLast() }.reversed()
        let name = ctx.name?.getText() ?? ""
        let typeParams = ctx.generics.compactMap { $0.getText() }

        let decl = Decl.declFunGeneric(
            name: name,
            typeParams: typeParams,
            paramDecls: Array(params),
            returnType: returnType,
            localDecls: Array(localDecls),
            returnExpr: returnExpr,
            position: getPosition(ctx)
        )

        declStack.append(decl)
    }

    // MARK: - Stage 3: Expressions (#universal-types)

    /// generic [X, Y] expr — type abstraction
    override func exitTypeAbstraction(_ ctx: stellaParser.TypeAbstractionContext) {
        guard let body = exprStack.popLast() else {
            fatalError("Missing body in type abstraction")
        }
        let typeVars = ctx.generics.compactMap { $0.getText() }
        exprStack.append(.typeAbstraction(typeVars: typeVars, body: body, getPosition(ctx)))
    }

    /// expr[T1, T2] — type application
    override func exitTypeApplication(_ ctx: stellaParser.TypeApplicationContext) {
        let typeCount = ctx.types.count
        let types = (0..<typeCount).compactMap { _ in typeStack.popLast() }.reversed()

        guard let expr = exprStack.popLast() else {
            fatalError("Missing expression in type application")
        }

        exprStack.append(.typeApplication(expr: expr, types: Array(types), getPosition(ctx)))
    }

    // MARK: - Stage 2: Types (#references, #top-type, #bottom-type)
    
    /// &T — reference type
    override func exitTypeRef(_ ctx: stellaParser.TypeRefContext) {
        guard let innerType = typeStack.popLast() else {
            fatalError("Missing inner type in TypeRef")
        }
        typeStack.append(.ref(innerType))
    }
    
    /// Top — top type
    override func exitTypeTop(_ ctx: stellaParser.TypeTopContext) {
        typeStack.append(.top)
    }
    
    /// Bot — bottom type
    override func exitTypeBottom(_ ctx: stellaParser.TypeBottomContext) {
        typeStack.append(.bot)
    }
    
    // MARK: - Stage 2: Declarations (#exception-type-declaration)
    
    /// exception type = T
    override func exitDeclExceptionType(_ ctx: stellaParser.DeclExceptionTypeContext) {
        guard let exType = typeStack.popLast() else {
            fatalError("Missing type in exception type declaration")
        }
        declStack.append(.declExceptionType(type: exType, position: getPosition(ctx)))
    }
    
    // MARK: - Stage 2: Expressions (#references)
    
    /// new(expr) — allocate a reference cell
    override func exitRef(_ ctx: stellaParser.RefContext) {
        guard let expr = exprStack.popLast() else {
            fatalError("Missing expression in Ref (new)")
        }
        exprStack.append(.newRef(expr, getPosition(ctx)))
    }
    
    /// *expr — dereference a reference cell
    override func exitDeref(_ ctx: stellaParser.DerefContext) {
        guard let expr = exprStack.popLast() else {
            fatalError("Missing expression in Deref")
        }
        exprStack.append(.deref(expr, getPosition(ctx)))
    }
    
    /// lhs := rhs — assign to a reference cell
    override func exitAssign(_ ctx: stellaParser.AssignContext) {
        guard let rhs = exprStack.popLast(),
              let lhs = exprStack.popLast() else {
            fatalError("Missing operands in Assign")
        }
        exprStack.append(.assign(lhs: lhs, rhs: rhs, getPosition(ctx)))
    }
    
    /// @address — explicit memory address literal
    override func exitConstMemory(_ ctx: stellaParser.ConstMemoryContext) {
        let addr = ctx.mem?.getText() ?? "@0"
        exprStack.append(.constMemory(addr, getPosition(ctx)))
    }
    
    // MARK: - Stage 2: Expressions (#panic)
    
    /// panic! — unrecoverable error (diverges, has any type)
    override func exitPanic(_ ctx: stellaParser.PanicContext) {
        exprStack.append(.panic_(getPosition(ctx)))
    }
    
    // MARK: - Stage 2: Expressions (#exceptions)
    
    /// throw(expr)
    override func exitThrow(_ ctx: stellaParser.ThrowContext) {
        guard let expr = exprStack.popLast() else {
            fatalError("Missing expression in Throw")
        }
        exprStack.append(.throw_(expr, getPosition(ctx)))
    }
    
    /// try { tryExpr } with { fallbackExpr }
    override func exitTryWith(_ ctx: stellaParser.TryWithContext) {
        guard let fallback = exprStack.popLast(),
              let tryExpr = exprStack.popLast() else {
            fatalError("Missing expressions in TryWith")
        }
        exprStack.append(.tryWith(tryExpr: tryExpr, fallbackExpr: fallback, getPosition(ctx)))
    }
    
    /// try { tryExpr } catch { pat => fallbackExpr }
    override func exitTryCatch(_ ctx: stellaParser.TryCatchContext) {
        guard let fallback = exprStack.popLast(),
              let pat = patternStack.popLast(),
              let tryExpr = exprStack.popLast() else {
            fatalError("Missing parts in TryCatch")
        }
        exprStack.append(.tryCatch(tryExpr: tryExpr, pattern: pat, fallbackExpr: fallback, getPosition(ctx)))
    }
    
    // MARK: - Stage 2: Expressions (#type-cast)
    
    /// expr cast as Type
    override func exitTypeCast(_ ctx: stellaParser.TypeCastContext) {
        guard let type = typeStack.popLast(),
              let expr = exprStack.popLast() else {
            fatalError("Missing expression or type in TypeCast")
        }
        exprStack.append(.typeCast(expr: expr, type: type, getPosition(ctx)))
    }
}

// MARK: - Convenience Function

/// Builds AST from Stella source code
func buildAST(from code: String) throws -> Program {
    let input = ANTLRInputStream(code)
    let lexer = stellaLexer(input)
    let tokens = CommonTokenStream(lexer)
    let parser = try stellaParser(tokens)
    
    // Disable standard error listeners for quieter behavior
    parser.removeErrorListeners()
    
    let tree = try parser.start_Program()
    
    let builder = ASTBuilder()
    let walker = ParseTreeWalker()
    try walker.walk(builder, tree)
    
    guard let program = builder.program else {
        throw StellaError.parsingFailed("Failed to build AST from parse tree")
    }
    
    return program
}

// MARK: - Error Types

enum StellaError: Error, CustomStringConvertible {
    case parsingFailed(String)
    
    var description: String {
        switch self {
        case .parsingFailed(let msg):
            return "Parsing failed: \(msg)"
        }
    }
}
